= Animations from Sprite Sheets
:source-highlighter: highlight.js

Source code for and a basic demonstration of generating animations based on
`png` or `jpg` sprite sheet files.

[source, python]
----
image explosion = spritesheet_animation("images/explosion.png", 8, 6)
----

== The `spritesheet_animation` Function

Generates an animation from the given sprite file path.  The given path MUST be
a valid path relative to the game directory including the file extension, e.g.
`"images/explosion.png"`.

This method supports the following file types: `[ "png", "jpg" ]`

.Arguments
--
[cols="1m,1m,8"]
|===

| image_path
| str
| The path to the sprite sheet image file relative to the game directory.  This
  path **MUST** include the file extension.  Example: `"images/explosion.png"`.

| x_sprite_count
| int
| Number of sprites the sprite sheet has along the x-axis.

| y_sprite_count
| int
| Number of sprites the sprite sheet has along the y-axis.
|===
--

.Keyword Arguments
--
[cols="1m,1m,8"]
|===

| fps
| int\|float
| Frames per second for the animation. Incompatible with the `pause` keyword
  argument; setting both will cause an error. Defaults to 30.

| pause
| float
| How long to pause between each frame. Incompatible with the `fps` keyword
  argument; setting both will cause an error. Defaults to None.

| looping
| bool
| Whether the animation should loop.  Defaults to `False`.

| hold_last_frame
| bool
| Whether the animation should hold on the last frame or "vanish" after the last
  frame has played.  Defaults to `False` (vanishing).
|===
--

== Credits

* `__get_image_size` adapted from an answer on
  link:https://stackoverflow.com/a/20380514[this StackOverflow question].
* `explosion.png` from https://www.pngegg.com/en/png-nvowz

== License

Published under the link:license[MIT License] which practically says "go nuts,
use it however you want."
